---
# tasks - main.yml for nerve4-docker

- include: rhel-install-docker.yml
  when: 
    (ansible_distribution == "CentOS") or
    (ansible_distribution == "RedHat") or
    (ansible_distribution in "Rocky")

- include: ubuntu-install-docker.yml
  when: 
    - ansible_distribution == "Ubuntu"

- include: run-docker.yml